services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
      - "--cleanup"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  database:
    image: postgres:17
    container_name: api_database
    restart: always
    secrets:
      - db-password
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      POSTGRES_DB: postgres
    volumes:
      - database_volume:/var/lib/postgresql/data
    networks:
      - api_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5


  api:
    container_name: FastAPI
    image: ouslan/jp-api:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
    secrets:
      - db-password
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      POSTGRES_DB: postgres

    volumes:
      - data_folder:/app/data
    ports:
      - 8051:8000
    networks:
      - api_network
    depends_on:
      database:
        condition: service_healthy

networks:
  api_network:

volumes:
  database_volume:
  data_folder:

secrets:
  db-password:
    file: ~/db/password.txt
