services:
  database:
    image: postgres:17
    container_name: api_database
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      TIMESCALEDB_TELEMETRY: off
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - database_volume:/var/lib/postgresql/data
    networks:
      - api_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5

  webapp:
    container_name: FastAPI
    build:
      context: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - data_folder:/app/data 
    ports:
      - 8051:8000
    networks:
      - api_network
    depends_on:
      database:
        condition: service_healthy

networks:
  api_network:

volumes:
  database_volume:
  data_folder:
