name: Build Docker Image for Staging

on: 
  workflow_dispatch:
  
  push:
    branches:
      - 'STAGING'
env:
  DOCKER_IMAGE_NAME: ouslan/jp-api
  DOCKER_REGISTRY_URL: hub.docker.com

jobs:
  build_docker_images:
    # Job name that shows in the GitHub UI
    name: Build Docker Images
    # Runner to use
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag stage

    - name: Puch the Docker image
      run: docker push $DOCKER_REGISTRY_URL/$DOCKER_IMAGE_NAME:stage

    - name: Remove the local image
      run: docker rmi $DOCKER_IMAGE_NAME:$RELEASE_VERSION

    - name: Prune Docker
      run: docker system prune -a -f
