
name: Staging Docker Image

on:
  push:
    branches:
      - 'main'
      - '31-docker'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:testing
          # Optionally, add more tags
          # tags: |
          #   ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
          #   ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}

