name: Staging Docker Image

on:
  push:
    branches:
      - 'main'
      - '31-docker'

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker Image
      run: |
        docker build . --tag ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:testing

